---
title: "Fall 2020 Calendar for 431"
output: 
    html_document:
        toc: true
        toc_float: true
---

## General Comments {-}

- All class sessions will be held from **1:00 to 2:15 PM** via Zoom. 
- All times listed anywhere on this page refer to **US Eastern Time**.
- The Zoom link for each class is [available on Canvas](https://canvas.case.edu) in the Announcements section, as are details on Teaching Assistant Office Hours. Zoom recordings are also posted to [Canvas](https://canvas.case.edu).
- All Zoom class session will open 15 minutes before class begins and close 15 minutes after class ends for students to ask questions of Professor Love.
- Links to Class sessions and Assignments will appear here as the materials become available.

## Readings

The two required purchases (described in [the Syllabus](https://thomaselove.github.io/431-2020-syllabus/)) are:

- *Spiegelhalter* which refers to *The Art of Statistics* by David Spiegelhalter
- *Leek* which refers to *The Elements of Data Analytic Style* by Jeffrey Leek

Please feel free to read ahead of our suggested pace in the Calendar below. Note that the *Leek* book is much shorter than the *Spiegelhalter*.

In addition, we also **strongly** encourage you to read [R for Data Science](https://r4ds.had.co.nz). 

- We suggest reading things that interest you from the Explore section (chapters 1-8) and the Communicate section (chapters 26-28, in particular) before Project A.
- We suggest adding in some of the Wrangle section (particularly chapters 9-12, 15 and 16) and the rest of the Communicate section before Project B.

## November 2020

LINK | Date | Description
--------: | -------: | :---------------------------------------------------------
\- | Tue 11-03 | **No 431 Class or Office Hours**. US Election Day
\- | Wed 11-04 | *TA office hours resume*
[Class 20](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class20) | Thu 11-05 | Comparing Proportions, Two-Way and Three-Way Tables
\- | Fri 11-06 | *Spiegelhalter* Chapter 11
\- | Sat 11-07 | [Project B instructions](https://thomaselove.github.io/431-2020-projectB/) are now available.
\- | Mon 11-09 | **[Lab 6 due](https://github.com/THOMASELOVE/431-2020/blob/master/labs/README.md)** at 9 PM 
[Class 21](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class21) | Tue 11-10 | Power and Sample Size Considerations
\-  | Wed 11-11 | **[Project B Class Survey](http://bit.ly/431-projectB-survey)** due at 11 PM.
[Class 22](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class22) | Thu 11-12 | Box-Cox, Transformation in Regression
\- | Fri 11-13 | *Spiegelhalter* Chapter 12
\- | Mon 11-16 | **[Lab 7 due](https://github.com/THOMASELOVE/431-2020/blob/master/labs/README.md)** at 9 PM 
[Class 23](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class23) | Tue 11-17 | Stepwise Regression, Residual Plots in Regression
\-  | Wed 11-18 | **[Minute Paper after Class 23](https://github.com/THOMASELOVE/431-2020/blob/master/minutepapers/README.md)** due at Noon 
\- | Thu 11-19 | **[Project B Study 2 Data Plan](http://bit.ly/431-projectB-data-plan)** due at Noon
[Class 24](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class24) | Thu 11-19 | Cross-Validation in Prediction Models (MAPE, RMSPE, etc.)
\- | Fri 11-20 | *Last day of TA office hours until 2020-11-28*
\- | Tue 11-24 | **CWRU Holiday** (Thanksgiving Week)
\- | Thu 11-26 | **CWRU Holiday** (Thanksgiving Week)
\- | Sat 11-28 | *TA office hours begin again*
\- | Sun 11-29 | *Spiegelhalter* complete the book
\- | Mon 11-30 | **[Lab 8 due](https://github.com/THOMASELOVE/431-2020/blob/master/labs/README.md)** at 9 PM 

## December 2020

LINK | Date | Description
--------: | -----: | :---------------------------------------------------------
[Class 25](https://github.com/THOMASELOVE/431-2020/blob/master/classes/class25) | Tue 12-01 | Details for Project B oral presentations, and more
\-  | Wed 12-02 | **[Minute Paper after Class 25](https://github.com/THOMASELOVE/431-2020/blob/master/minutepapers/README.md)** due at Noon 
[Class 26](https://github.com/THOMASELOVE/431-2020/blob/master/classes/class26) | Thu 12-03 | Last 431 Class
\- | Fri 12-04 | *Quiz 2 will be made available*
\- | Mon 12-07 | *Final Day of TA office hours* for the semester
\- | Thu 12-10 | **[Project B](https://thomaselove.github.io/431-2020-projectB)** due at Noon (uses Classes 01-24)
\- | Thu 12-10 | [Lab Regrade Request Form](http://bit.ly/431-2020-lab-regrade-requests) due at Noon (optional)
\- | Mon 12-14 | **Quiz 2 due** at Noon (material from Classes 01-24)

## End of Semester

- Most Project B groups will give their oral presentation through a video recording.
- About 12 groups (which groups will be announced on 2020-12-01) will have Zoom meetings with Dr. Love to present their Project B on 2020-12-09, 12-10 or 12-11.
- The end of the University Final Exam period is 2020-12-16.

## TA Office Hours

TA office hours begin on 2020-08-31. They will be held every day until 2020-12-07 with the exceptions of 2020-11-03 (Election Day) and the Thanksgiving Break (2020-11-21 through 2020-11-27).

The Zoom information for TA office hours is posted in the [Announcements section on Canvas](https://canvas.case.edu). Here's the schedule...

Day | Morning | Mid-Day | Evening
---: | ------- | ------ | -------
Mondays | 10:30 AM to Noon | 3:00 to 4:30 PM | 7:00 to 8:30 PM
Tuesdays | - | 2:30 to 4:00 PM | -
Wednesdays | 9:30 to 11:00 AM | - | 6:30 to 8:00 PM
Thursdays | - | - | 8:30 to 10:00 PM
Fridays | 9:00 to 10:30 AM | 11:30 AM to 1:00 PM | 3:30 to 5:00 PM
Saturdays | 10:30 to 11:30 AM | - | -
Sundays | 10:30 to 11:30 AM | - | 6:30 to 8:00 PM

Note that we've canceled Thursday morning office hours effective 2020-10-08.

## Completed Materials

## August 2020

LINK | Date | Description
--------: | --------: | :-------------------------------------------------------
[Class 01](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class01) | Tue 08-25 | Welcome to PQHS / CRSP / MPHP 431!
[Class 02](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class02) | Thu 08-27 | Start of Part A: Data Visualization, Working with R & RStudio
\- | Fri 08-28 | Read [the Syllabus](https://thomaselove.github.io/431-2020-syllabus/) and *Leek* (intro and sections 1-3)
\- | Mon 08-31 | *First Day of TA Office Hours*

## September 2020

LINK | Date | Description
--------: | --------: | :-------------------------------------------------------
[Class 03](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class03) | Tue 09-01 | Using R, RStudio and R Markdown: Getting Started
\-  | Wed 09-02 | **[Minute Paper after Class 03](https://github.com/THOMASELOVE/431-2020/blob/master/minutepapers/README.md)** due at Noon
[Class 04](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class04) | Thu 09-03 | Visualizing and Managing the "Short" Survey with the Tidyverse
\-  | Fri 09-04 | *Spiegelhalter* Introduction, *Leek* sections 4-5
\- | Sat 09-05 | By now, R should be installed and running for you well
\- | Mon 09-07 | **[Lab 01 due](https://github.com/THOMASELOVE/431-2020/blob/master/labs/README.md)** at 9 PM
[Class 05](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class05) | Tue 09-08 | More Complex Visualizations and Tables
\-  | Wed 09-09 | **[Minute Paper after Class 05](https://github.com/THOMASELOVE/431-2020/blob/master/minutepapers/README.md)** due at Noon
[Class 06](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class06)  | Thu 09-10 | Assessing Normality, Thinking about Associations
\-  | Fri 09-11 | *Spiegelhalter* Chapters 1-3, *Leek* sections 9-10
\- | Mon 09-14 | **[Lab 02 due](https://github.com/THOMASELOVE/431-2020/blob/master/labs/README.md)** at 9 PM 
[Class 07](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class07) | Tue 09-15 | Working with NHANES Blood Pressures
\-  | Wed 09-16 | **[Minute Paper after Class 07](https://github.com/THOMASELOVE/431-2020/blob/master/minutepapers/README.md)** due at Noon 
[Class 08](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class08) | Thu 09-17 | Normality, Scatterplots, Correlation, Linear Regression
\-  | Fri 09-18 | *Spiegelhalter* Chapters 4 and 7, *Leek* sections 11-12
\- | Mon 09-21 | **[Lab 3 due](https://github.com/THOMASELOVE/431-2020/blob/master/labs/README.md)** at 9 PM 
[Class 09](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class09) | Tue 09-22 | Linear Regression Models, Working with Scatterplots, Predictions, Residuals
\-  | Wed 09-23 | **[Minute Paper after Class 09](https://github.com/THOMASELOVE/431-2020/blob/master/minutepapers/README.md)** due at Noon 
[Class 10](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class10) | Thu 09-24 | Linear Regression Models, Making Inferences, Using Factors
\-  | Fri 09-25 | *Spiegelhalter* Chapters 8-9, *Leek* sections 13-14
\- | Mon 09-28 | **[Lab 4 due](https://github.com/THOMASELOVE/431-2020/blob/master/labs/README.md)** at 9 PM 
[Class 11](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class11) | Tue 09-29 | Multiple Linear Regression, Categorical Predictors
\-  | Wed 09-30 | **[Minute Paper after Class 11](https://github.com/THOMASELOVE/431-2020/blob/master/minutepapers/README.md)** due at Noon 

## October 2020

LINK | Date | Description
--------: | --------: | :-------------------------------------------------------
[Class 12](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class12) | Thu 10-01 | Multiple Linear Regression, Holdout Sample, Box-Cox and Tukey's Ladder
\- | Fri 10-02 | **[Project A proposal](https://thomaselove.github.io/431-2020-projectA/)** due at noon, *[Quiz 1](https://github.com/THOMASELOVE/431-2020/blob/master/quizzes/quiz1/quiz1.md) will be available*, Finish *Leek*.
[Class 13](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class13) | Tue 10-06 | Comparing Groups, 1: Statistical Significance, P values
\- | Wed 10-07 | **[Quiz 1](https://github.com/THOMASELOVE/431-2020/blob/master/quizzes/quiz1/quiz1.md) due** at Noon (material from Classes 01-12)
[Class 14](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class14) | Thu 10-08 | Comparing Groups, 2
\- | Fri 10-09 | *Spiegelhalter* Chapters 5-6
[Class 15](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class15) | Tue 10-13 | Comparing Groups, 3
\-  | Wed 10-14 | **[Minute Paper after Class 15](https://github.com/THOMASELOVE/431-2020/blob/master/minutepapers/README.md)** due at Noon 
\- | Thu 10-15 | **No 431 Class**. Dr. Love will be at AHRQ Study Section.
[Class 16](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class16) | Tue 10-20 | Comparing Means using Independent Samples (t, bootstrap, rank sum)
[Class 17](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class17) | Thu 10-22 | One-Factor Analysis of Variance, plus Multiple Comparisons
\- | Fri 10-23 | *Spiegelhalter* Chapter 10 
\- | Mon 10-26 | **[Lab 5 due](https://github.com/THOMASELOVE/431-2020/blob/master/labs/README.md)** at 9 PM 
[Class 18](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class18) | Tue 10-27 | Comparing Means with Paired Samples
\-  | Wed 10-28 | **[Minute Paper after Class 18](https://github.com/THOMASELOVE/431-2020/blob/master/minutepapers/README.md)** due at Noon 
[Class 19](https://github.com/THOMASELOVE/431-2020/tree/master/classes/class19) | Thu 10-29 | Comparing Rates/Percentages/Proportions
\- | Fri 10-30 | **[Project A due](https://thomaselove.github.io/431-2020-projectA/)** at 5 PM (note change of date)
