---
title: "Contact Information"
---

If you've spent 15 minutes working on something and are stuck, don't keep working on it. ASK FOR HELP. To get help in this course, you have three main options:

1. Use our [Piazza](https://piazza.com/case/fall2020/pqhs431) discussion board to ask (and answer) questions about the course. This is available 24 hours a day, 7 days a week.

2. Attend TA office hours to get one-on-one help or share a computer problem.
    - TA office hours begin on 2020-08-31. They will be held every day until 2020-12-07 with the exceptions of 2020-11-03 (Election Day) and the Thanksgiving Break (2020-11-21 through 2020-11-27).
    - The weekly schedule for TA office hours (with Zoom information) is posted in the [Announcements section on Canvas](https://canvas.case.edu), and also below.
    - The schedule of TA office hours follows. All times Eastern Time.
        - **Mondays** 10:30 AM to Noon, 3:00 to 4:30 PM, 7:00 to 8:30 PM
        - **Tuesdays** 2:30 to 4:00 PM
        - **Wednesdays** 9:30 to 11:00 AM, 6:30 to 8:00 PM
        - **Thursdays** 8:30 to 10:00 PM
        - **Fridays** 9:00 to 10:30 AM, 11:30 AM to 1:00 PM, 3:30 to 5:00 PM
        - **Saturdays** 10:30 to 11:30 AM
        - **Sundays** 10:30 to 11:30 AM, 6:30 to 8:00 PM
    - For Zoom links to these sessions, visit the [Announcements section on Canvas](https://canvas.case.edu).
    
Dr. Love will also hold "office hours" for the 15 minutes before and after each class on Zoom.

3. Email Dr. Love at **Thomas dot Love at case dot edu** with any individual concerns related to the course that you cannot ask elsewhere, if you have any special concerns or needs that you want him to know about, or to set up an appointment with him for a Zoom meeting.

